export default function Analysis() {
  return (
    <div className="min-h-screen bg-main-gradient py-12 px-6">

      <div className="max-w-7xl mx-auto">

        {/* TITLE */}

        <h1 className="text-4xl font-bold text-white text-center mb-12">
          AI Resume Analysis Dashboard
        </h1>

        {/* GRID */}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">

          {/* ATS CARD */}

          <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-xl p-6 hover:scale-105 transition">
            <h2 className="text-xl font-semibold text-sky-300 mb-3">
              ATS Score
            </h2>

            <p className="text-slate-300 text-sm">
              Your resume compatibility score with modern ATS systems.
            </p>
          </div>

          {/* SKILLS CARD */}

          <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-xl p-6 hover:scale-105 transition">
            <h2 className="text-xl font-semibold text-emerald-300 mb-3">
              Skills Analysis
            </h2>

            <p className="text-slate-300 text-sm">
              Detected skills and missing skills extracted from your resume.
            </p>
          </div>

          {/* JOB MATCH CARD */}

          <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-xl p-6 hover:scale-105 transition">
            <h2 className="text-xl font-semibold text-yellow-300 mb-3">
              Job Match
            </h2>

            <p className="text-slate-300 text-sm">
              Match score between your resume and a selected job description.
            </p>
          </div>

          {/* KEYWORD CARD */}

          <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-xl p-6 hover:scale-105 transition">
            <h2 className="text-xl font-semibold text-purple-300 mb-3">
              Keyword Analytics
            </h2>

            <p className="text-slate-300 text-sm">
              Frequency and optimization of important resume keywords.
            </p>
          </div>

          {/* AI SUGGESTIONS */}

          <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-xl p-6 hover:scale-105 transition md:col-span-2 lg:col-span-1">
            <h2 className="text-xl font-semibold text-cyan-300 mb-3">
              AI Suggestions
            </h2>

            <p className="text-slate-300 text-sm">
              Smart improvements generated by AI to strengthen your resume.
            </p>
          </div>

        </div>

      </div>

    </div>
  );
}